export const CAT_CATEGORIES_REQUEST = 'CAT_CATEGORIES_REQUEST'
export const CAT_CATEGORIES_SUCCESS = 'CAT_CATEGORIES_SUCCESS'
export const CAT_CATEGORIES_FAIL = 'CAT_CATEGORIES_FAIL'

export const CAT_CATEGORY_IMAGE_REQUEST = 'CAT_CATEGORY_IMAGE_REQUEST'
export const CAT_CATEGORY_IMAGE_SUCCESS = 'CAT_CATEGORY_IMAGE_SUCCESS'

export const CAT_IMAGES_REQUEST = 'CAT_IMAGES_REQUEST'
export const CAT_IMAGES_SUCCESS = 'CAT_IMAGES_SUCCESS'
export const CAT_IMAGES_FAIL = 'CAT_IMAGES_FAIL'
export const REMOVE_CAT_IMAGES = 'REMOVE_CAT_IMAGES'

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
export const REMOVE_SELECTED_CATEGORY = 'REMOVE_SELECTED_CATEGORY'